### ISSUE TITLE
“Apply changes” sticks around after changing views

### ISSUE THREAD

**Issue by chasenlehara** [canjs/devtools#68]
Steps to reproduce:

1. Click on a component
2. Edit a value in its VM
3. Change views / select a different component

Expected results: if it’s a _feature_ that you can change different things and then apply changes all at once, then that should work (right now both VMs get the key set to undefined), otherwise the changes should be discarded.

![apply changes bug](https://user-images.githubusercontent.com/10070176/52081911-3fd44c80-2550-11e9-8727-11a27829dff3.gif)

**Comment by phillipskevin** [comment]
@chasenlehara would you mind adding a key to the second viewmodel and see if this still happens?

**Comment by chasenlehara** [comment]
It looks like adding another key doesn’t cause the bug.
![again](https://user-images.githubusercontent.com/10070176/52090679-e9bed380-2566-11e9-9a55-54f6d558b7a0.gif)

**Comment by phillipskevin** [comment]
The issue here is that the `selectedNode` is not being cleared. When the node is reset, the `jsonPatches` that enable/disbale the "Apply Changes" button are cleared. 

I have a failing test for this on https://github.com/canjs/can-devtools-components/tree/unset-selected-node. I should be able to fix it today or tomorrow.
