### ISSUE TITLE
Breakpoints multiply in editor when devtools is opened.

### ISSUE THREAD

**Issue by bmomberger-bitovi** [canjs/devtools#90]
Repro steps:

- install devtools as a Chrome extension
- open a page with CanJS components (tested with panel/panel.html from this repo)
- open Chrome dev tools
- click CanJS in dev tools top nav
- click a component in the components tree
- expand the Breakpoints editor
- type any property in the breakpoints
- right-click anywhere in the CanJS devtools' panels
- click "inspect"

Expected outcome
- The Chrome dev tools for the CanJS dev tools window opens
- The number of breakpoints in the CanJS dev tools' breakpoints editor stays the same

Actual outcome
- The Chrome dev tools for the CanJS dev tools window opens
- The number of breakpoints in the CanJS dev tools' breakpoints editor doubles.

Additionally, clicking CanJS in the second dev tools window (the one spawned by inspecting in CanJS dev tools) will cause yet more of the same breakpoints to be added.

**Comment by phillipskevin** [comment]
This is happening because any time one of the panels in devtools needs to run a function in the user's window, it goes through this code in the `runDevtoolsFunction` helper: https://github.com/canjs/devtools/blob/d9a04dd8c2a277db6f1f482b57ca755320cc2050/canjs-devtools-helpers.mjs#L116-L119

This code adds the function (the function that needs to run in the user's page) to the `frameChangeHandlers` array so that when frames are added or removed the function can be run again (see https://github.com/canjs/devtools/issues/71).

The problem is the `addBreakpoint` function does not need to re-run whenever frames change. The `onFrameChange(frameChangeHandler)` should only be called if `options.refreshInterval` is set.
